#!/bin/sh

# 第一引数のディレクトリに対してコンテナからmake <args>を実行する
# 未完成
if [[ ! -d $1 ]]; then
	echo "Usage:dmake <target dir> <option>"
else 
	dirpath=$($PWD/$1)
	echo $dirpath
	command=""
	if [ $# != 1 ]; then
		for i in $@
		do
			if [ $i != $1 ]; then
				command="$command $i"
			fi
		done		
	fi
# 絶対パスが必要?
	docker run --rm -v $dirpath:$dirpath -w $dirpath compilerbook make $command
fi
